apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-secret
  namespace: wallabag
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: SYMFONY__ENV__SECRET
      remoteRef:
        key: /wallabag/secret
        property: secret
