apiVersion: v1
kind: Secret
metadata:
  name: dex-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    homelab.khuedoan.com/bao-secret: "true"
  annotations:
    secrets-webhook.security.bank-vaults.io/provider: bao
    secrets-webhook.security.bank-vaults.io/bao-role: {{ .Release.Namespace }}
    secrets-webhook.security.bank-vaults.io/bao-path: kubernetes
    secrets-webhook.security.bank-vaults.io/bao-serviceaccount: default
data:
  # Connectors
  KANIDM_CLIENT_ID: {{ "bao:secret/data/kanidm.dex#client_id" | b64enc | quote }}
  KANIDM_CLIENT_SECRET: {{ "bao:secret/data/kanidm.dex#client_secret" | b64enc | quote }}
  # Clients
  GRAFANA_SSO_CLIENT_SECRET: {{ "bao:secret/data/dex.grafana#client_secret" | b64enc | quote }}
  FORGEJO_CLIENT_SECRET: {{ "bao:secret/data/dex.forgejo#client_secret" | b64enc | quote }}
