apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: vaultwarden
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: vaultwarden.vaultwarden
        property: ADMIN_TOKEN
