apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: telegram-bot-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: telegram-bot-secret
    template:
      data:
        BOT_TOKEN: {{`"{{ .token }}"`}}
        MONGO_URI: 'mongodb://{{`{{ .username }}`}}:{{`{{ .password }}`}}@mongo'
  data:
    - secretKey: token
      remoteRef:
        key: /telegram-bot/bot-token
        property: token
    - secretKey: password
      remoteRef:
        key: /telegram-bot/mongodb
        property: password
    - secretKey: username
      remoteRef:
        key: /telegram-bot/mongodb
        property: username
