apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.renovate.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: {{` "{{ .token }}" `}}
  data:
    - secretKey: token
      remoteRef:
        key: /gitea/renovate
        property: token
