apiVersion: v2
name: istio
version: 0.0.0
dependencies:
  - name: base
    version: 1.30.5
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.30.5
    repository: https://istio-release.storage.googleapis.com/charts
