- name: Install OS on bare-metal machines
  hosts: all
  gather_facts: no
  vars_prompt:
    - name: username
      prompt: Enter username for metal nodes
      private: no
    - name: password
      prompt: Enter password for metal nodes
  roles:
    - pxe-boot

- name: Provision
  hosts: all
  vars_prompt:
    - name: lxd_password
      prompt: Enter password for LXD server
  roles:
    - snap
    - lxd
