all:
  vars:
    secondary_gateway: 192.168.200.1
    control_plane_endpoint: 192.168.1.110
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: '00:23:24:d1:f5:69', disk: sda, network_interface: eno1, secondary_interface: enp2s0, secondary_interface_ip: '192.168.200.110/24'}
        metal1: {ansible_host: 192.168.1.111, mac: '00:23:24:d1:f3:f0', disk: sda, network_interface: eno1, secondary_interface: enp2s0, secondary_interface_ip: '192.168.200.111/24'}
        metal2: {ansible_host: 192.168.1.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1, secondary_interface: enp2s0, secondary_interface_ip: '192.168.200.112/24'}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1, secondary_interface: enp2s0, secondary_interface_ip: '192.168.200.113/24'}
