metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.200, mac: 'ec:b1:d7:6b:29:cf', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.1.201, mac: 'ec:b1:d7:6b:2e:ee', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.1.202, mac: 'ec:b1:d7:6b:40:cd', disk: sda, network_interface: eno1}
