metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.20, mac: '34:17:eb:d6:0e:0e', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.0.21, mac: '34:17:eb:cc:21:da', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.0.22, mac: '34:17:eb:d6:0f:76', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.0.23, mac: '34:17:eb:cc:21:08', disk: sda, network_interface: eno1}
