metal:
  children:
    masters:
      hosts:
        metal1: {ansible_host: 192.168.1.101, mac: 'b0:4f:13:06:82:1d', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.1.102, mac: 'b0:4f:13:06:08:33', disk: sda, network_interface: eno1}
        metal3: {ansible_host: 192.168.1.103, mac: 'b0:4f:13:06:82:ee', disk: sda, network_interface: eno1}
