all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.66, mac: '6c:4b:90:2a:6a:97', disk: sda, network_interface: eth0}
        metal1: {ansible_host: 192.168.1.94, mac: '6c:4b:90:2e:8d:82', disk: sda, network_interface: eth0}
        metal2: {ansible_host: 192.168.1.77, mac: '00:23:24:e7:21:e1', disk: sda, network_interface: eth0}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.1.86, mac: '00:23:24:e7:21:1b', disk: sda, network_interface: eth0}
