apiVersion: workflows.tekton.dev/v1alpha1
kind: Workflow
metadata:
  name: pull-request
  namespace: tekton-workflows
spec:
  triggers:
    - event:
        type: pull_request
        secret:
          secretName: webhook-secret
          secretKey: token
      bindings:
        - name: git_url
          value: $(body.repository.clone_url)
        - name: git_revision
          value: $(body.pull_request.head.sha)
  params:
    - name: git_url
      # TODO don't need default, but invalid mem address if remove this
      default: https://git.khuedoan.com/foo/bar
    - name: git_revision
      default: master
  pipelineRef:
    resolver: git
    params:
      # TODO ???
      # supposed to be param. or body., looks like it's not working in v1alpha1 yet
      - name: url
        value: $(tt.params.git_url)
      - name: revision
        value: $(tt.params.git_revision)
      - name: pathInRepo
        value: .ci/pull-request.yaml
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
