apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  nextcloud-username: admin
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}2
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  dataFrom:
    - extract:
        key: nextcloud.nextcloud
  target:
    creationPolicy: Merge
