apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
    - name: source
  steps:
    - name: ansible
      image: cytopia/ansible-lint
      workingDir: /workspace/source/metal
      command:
        - ansible-lint
      args:
        - -v
    - name: yaml
      image: cytopia/yamllint
      command:
        - yamllint
      args:
        - .
    - name: terraform
      image: hashicorp/terraform:1.1.7
      command:
        - terraform
      args:
        - fmt
        - -recursive
        - -check
        - -diff
