app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: v1.126.1
          env:
            UPLOAD_LOCATION: "./library"
            DB_DATA_LOCATION: "./postgres"
            DB_USERNAME: postgres
            DB_DATABASE_NAME: immich
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: adminPassword
            IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
            IMMICH_PORT: 2283
            TZ: Europe/Berlin
        machine-learning:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v1.126.1
          env:
            TZ: Europe/Berlin
  service:
    main:
      ports:
        http:
          port: 2283
          protocol: HTTP
        machine-learning:
          port: 3003
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.meyeringh.org"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: &host gallery.meyeringh.org
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: immich-tls-certificate
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 20Gi
      retain: false
      advancedMounts:
        main:
          main:
            - path: /usr/src/app/library
              subPath: library
            - path: /usr/src/app/postgres
              subPath: postgres
          machine-learning:
            - path: /cache
              subPath: cache
