apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/name: bazarr
    backup: bazarr-zfs
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: config-bazarr-zfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-local-dataset
