app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/pairdrop
            tag: 1.10.7
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
          protocol: HTTP
  route:
    main:
      enabled: true
      kind: HTTPRoute
      parentRefs:
        - name: gateway
          namespace: istio-system
          sectionName: https
      hostnames:
        - drop.khuedoan.com
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - identifier: main
              port: 3000
