apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headplane-cookie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: headplane-cookie
  data:
    - secretKey: oidc_client_secret
      remoteRef:
        key: headplane.cookie
        property: cookie_secret
