apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: headplane-agent
rules:
- apiGroups: ['']
  resources: ['pods']
  verbs: ['get', 'list']
- apiGroups: ['apps']
  resources: ['deployments']
  verbs: ['get', 'list']
