# https://github.com/tailscale/tailscale/blob/main/docs/k8s/sa.yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: {{ .Release.Namespace }}
