apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: http://vault.vault:8200
      path: secret
      auth:
        kubernetes:
          mountPath: kubernetes
          role: allow-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
