apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: password
      remoteRef:
        key: /nextcloud/admin
        property: password
    - secretKey: username
      remoteRef:
        key: /nextcloud/admin
        property: username
    - secretKey: smtp_username
      remoteRef:
        key: /nextcloud/smtp
        property: username
    - secretKey: smtp_password
      remoteRef:
        key: /nextcloud/smtp
        property: password
    - secretKey: redis_password
      remoteRef:
        key: /nextcloud/redis
        property: password
    - secretKey: secret
      remoteRef:
        key: /nextcloud/encryption
        property: secret
    - secretKey: passwordsalt
      remoteRef:
        key: /nextcloud/encryption
        property: passwordsalt
