apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediastack-botdarr
  labels:
    app: botdarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botdarr
  template:
    metadata:
      labels:
        app: botdarr
    spec:
      containers:
      - name: botdarr
        image: shayaantx/botdarr:latest
        env:
          - name: MAX_DOWNLOADS_TO_SHOW
            value: "5"
          - name: SONARR_URL
            value: https://sonarr.tribz.cloud
          - name: SONARR_TOKEN
            value: "a97228fd3a8046499af2541eeb32be80"
          - name: SONARR_DEFAULT_PROFILE
            value: Any
          - name: SONARR_PATH
            value: /data/media/sonarr/
          - name: RADARR_URL
            value: https://radarr.tribz.cloud
          - name: RADARR_TOKEN
            value: "80b58a9140a4425592dd1803f9434376"
          - name: RADARR_DEFAULT_PROFILE
            value: Any
          - name: RADARR_PATH
            value: /data/media/radarr/
          - name: MATRIX_ROOM
            value: '!SJUyGAU028lzEpIb:matrix.tribz.cloud'
          - name: MATRIX_USERNAME
            value: botdarr
          - name: MATRIX_PASSWORD
            value: botdarrInvite123
          - name: MATRIX_HOME_SERVER_URL
            value: https://matrix.tribz.cloud
        ports:
        - containerPort: 80
