apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: woodpecker-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: WOODPECKER_GITEA_CLIENT
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: forgejo.woodpecker
        property: client_id
    - secretKey: WOODPECKER_GITEA_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: forgejo.woodpecker
        property: client_secret
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: woodpecker.agent
        property: secret
