apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-secret
  namespace: {{ .Release.Namespace }}
  labels:
    homelab.khuedoan.com/bao-secret: "true"
  annotations:
    secrets-webhook.security.bank-vaults.io/provider: bao
    secrets-webhook.security.bank-vaults.io/bao-role: {{ .Release.Namespace }}
    secrets-webhook.security.bank-vaults.io/bao-path: kubernetes
    secrets-webhook.security.bank-vaults.io/bao-serviceaccount: default
data:
  WOODPECKER_GITEA_CLIENT: {{ "bao:secret/data/forgejo.woodpecker#client_id" | b64enc | quote }}
  WOODPECKER_GITEA_SECRET: {{ "bao:secret/data/forgejo.woodpecker#client_secret" | b64enc | quote }}
  WOODPECKER_AGENT_SECRET: {{ "bao:secret/data/woodpecker.agent#secret" | b64enc | quote }}
