apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.forgejo.gitea.admin.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    homelab.khuedoan.com/bao-secret: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    secrets-webhook.security.bank-vaults.io/provider: bao
    secrets-webhook.security.bank-vaults.io/bao-role: {{ .Release.Namespace }}
    secrets-webhook.security.bank-vaults.io/bao-path: kubernetes
    secrets-webhook.security.bank-vaults.io/bao-serviceaccount: default
data:
  username: {{ "forgejo_admin" | b64enc | quote }}
  password: {{ "bao:secret/data/forgejo.admin#password" | b64enc | quote }}
