apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.forgejo.gitea.admin.existingSecret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        username: forgejo_admin
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: forgejo.admin
        property: password
