{{- if or .Values.configuration.organizations .Values.configuration.repositories }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config-source
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/config/*.go").AsConfig | indent 2 }}
{{ (.Files.Glob "files/config/go.*").AsConfig | indent 2 }}
  config.yaml: |
{{ toYaml .Values.configuration | indent 4 }}
{{- end }}
