apiVersion: v2
name: openbao
version: 0.0.0
dependencies:
  - name: vault-operator
    version: 1.24.1
    repository: oci://ghcr.io/bank-vaults/helm-charts
  - name: secrets-webhook
    version: 0.4.1
    repository: oci://ghcr.io/bank-vaults/helm-charts
