apiVersion: v2
name: nextcloud
version: 0.0.0
appVersion: 30.0.6
dependencies:
  - name: nextcloud
    version: 6.6.9
    repository: https://nextcloud.github.io/helm/
  - name: postgresql
    version: 15.5.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: 19.6.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: collabora-online
    version: 1.1.20
    repository: https://collaboraonline.github.io/online
    condition: collabora.enabled
    alias: collabora
