- name: Create Kubernetes cluster
  hosts: all
  serial: "{{ serial | default('100%') }}"
  vars:
    ansible_path: "{{ playbook_dir }}/../.."
  roles:
    - geerlingguy.ntp
    - k3s

- name: Label Kubernetes nodes
  ansible.builtin.import_playbook: k8s-node-labels.yml

- name: Setup Etcd backups
  ansible.builtin.import_playbook: backup-etcd.yml

- name: Setup democratic-csi user
  ansible.builtin.import_playbook: democratic-csi-user.yml

- name: Install zfs-exporter
  hosts: grigri
  roles:
    - zfs-exporter
