apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
    backup: gitea-zfs
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: data-gitea-zfs-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: zfs-local-dataset
