apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: homelab
spec:
  workspaces:
    - name: shared-data
  tasks:

    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: http://gitea-http.gitea:3000/ops/homelab
        - name: revision
          value: master

    - name: tools
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-data
        # TODO secure registry
        # - name: dockerconfig
        #   workspace: dockerconfig
      taskRef:
        name: kaniko
      params:
        - name: CONTEXT
          value: ./tools
        - name: IMAGE
          value: registry.khuedoan.com/tools:latest
        - name: EXTRA_ARGS
          value:
            - --cache=true

    # TODO lint
    - name: metal
      runAfter:
        - tools
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        stepTemplate:
          image: registry.khuedoan.com/tools:latest
          workingDir: /workspace/source/metal
          command:
            - make
        steps:
          - name: cluster
            args:
              - cluster

    - name: bootstrap
      runAfter:
        - tools
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        stepTemplate:
          image: registry.khuedoan.com/tools:latest
          workingDir: /workspace/source/bootstrap
          command:
            - make
        steps:
          - name: argocd
            args:
              - argocd
          - name: root
            args:
              - root

    - name: external
      runAfter:
        - tools
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        stepTemplate:
          image: registry.khuedoan.com/tools:latest
          workingDir: /workspace/source/external
          command:
            - make
        steps:
          - name: plan
            args:
              - plan
          - name: apply
            args:
              - apply
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: homelab
spec:
  pipelineRef:
    name: homelab
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
