apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubernetes-internal-ca-key-pair
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: kubernetes-internal-ca-key-pair
  data:
    - secretKey: tls.crt
      remoteRef:
        key: /cert-manager/internal-ca
        property: crt
    - secretKey: tls.key
      remoteRef:
        key: /cert-manager/internal-ca
        property: key
