apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudflare-api-token
  data:
    - secretKey: api-token
      remoteRef:
        key: /cert-manager/cloudflare
        property: token
