apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-data
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  # TODO: Move secrets storage to replicated storage with tested backups.
  storageClassName: local-path
