apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, create, update, patch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openbao
subjects:
  - kind: ServiceAccount
    name: openbao
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: openbao
    namespace: {{ .Release.Namespace }}
