apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/name: qbittorrent
    backup: qbittorrent-zfs
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: config-qbittorrent-zfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-local-dataset
