apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ .Release.Name }}
      sectionName: https
  validation:
    hostname: auth.khuedoan.com
    wellKnownCACertificates: System
    subjectAltNames:
      - type: Hostname
        hostname: auth.khuedoan.com
