#!/bin/sh

mkdir -p "${1}"

cat << EOT > "${1}/Chart.yaml"
apiVersion: v2
name: CHANGEME
version: 0.0.0
dependencies:
- name: CHANGEME
  version: CHANGEME
  repository: CHANGEME
EOT

touch "${1}/values.yaml"
