#!/bin/sh

CURRENT_DOMAIN="khuedoan.com"

git grep "${CURRENT_DOMAIN}" -- bootstrap system platform apps .tekton | cut -d ':' -f1 | uniq | while read p; do
  sed -i "s/${CURRENT_DOMAIN}/${1}/g" $p
done
