#!/usr/bin/python

import requests
import time

from kubernetes import client, config
from rich.console import Console

# Essential services
ingresses = [
    {
        'name': 'argocd-server',
        'fullname': 'ArgoCD',
        'namespace': 'argocd',
    },
    {
        'name': 'hajimari',
        'fullname': 'Homepage',
        'namespace': 'hajimari',
    }
]

config.load_kube_config(config_file='./metal/kubeconfig.yaml')


def wait_app(name: str, fullname: str, namespace: str) -> None:
    i = client.NetworkingV1Api().read_namespaced_ingress(
        name,
        namespace
    )

    host = i.spec.rules[0].host

    console = Console()

    with console.status(f"Waiting for {fullname}") as status:
        while requests.get(f"https://{host}", verify=False).status_code != 200:
            time.sleep(30)
        console.log(f"{fullname} is ready, visit https://{host}")


# TODO
# from concurrent.futures import ThreadPoolExecutor
# with ThreadPoolExecutor(max_workers=4) as pool:
#     # Number of tasks is greater than max workers
#     pool.map(wait_app, range(8))


requests.urllib3.disable_warnings()

for ingress in ingresses:
    wait_app(
        name=ingress['name'],
        fullname=ingress['fullname'],
        namespace=ingress['namespace'],
    )
