apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grafana-admin-secret
  data:
    - secretKey: username
      remoteRef:
        key: /grafana/admin
        property: username
    - secretKey: password
      remoteRef:
        key: /grafana/admin
        property: password
