- name: Install packages for automatic upgrade
  dnf:
    name:
      - dnf-automatic
      - dnf-utils

- name: Copy automatic upgrade config file
  copy:
    src: automatic.conf
    dest: /etc/dnf/automatic.conf
    mode: 0644

- name: Enable automatic upgrade service
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true
