apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: homelab
spec:
  workspaces:
    - name: shared-data
  tasks:

    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: http://gitea-http.gitea:3000/ops/homelab
        - name: revision
          value: master

    - name: tools
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-data
        # TODO secure registry
        # - name: dockerconfig
        #   workspace: dockerconfig
      taskRef:
        name: kaniko
      params:
        - name: CONTEXT
          value: ./tools
        - name: IMAGE
          value: registry.khuedoan.com/tools:latest
        - name: EXTRA_ARGS
          value:
            - --cache=true

    - name: lint
      runAfter:
        - tools
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        stepTemplate:
          image: registry.khuedoan.com/tools:latest
        steps:
          - name: ansible
            workingDir: /workspace/source/metal
            command:
              - ansible-lint
            args:
              - -v
              - --force-color
          - name: yaml
            workingDir: /workspace/source
            command:
              - yamllint
            args:
              - .
          - name: terraform
            workingDir: /workspace/source/external
            command:
              - terraform
            args:
              - fmt
              - -recursive
              - -check
              - -diff

    - name: metal
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        volumes:
          - name: ansible-secrets
            secret:
              secretName: ansible-secrets
              defaultMode: 0400
        stepTemplate:
          image: registry.khuedoan.com/tools:latest
          workingDir: /workspace/source/metal
          volumeMounts:
            - name: ansible-secrets
              mountPath: /root/.ssh/id_ed25519
              subPath: id_ed25519
          command:
            - make
        steps:
          - name: cluster
            args:
              - cluster

    - name: bootstrap
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        stepTemplate:
          image: registry.khuedoan.com/tools:latest
          workingDir: /workspace/source/bootstrap
          command:
            - make
        steps:
          - name: argocd
            args:
              - argocd
          - name: root
            args:
              - root

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: homelab
spec:
  serviceAccountName: tekton-admin
  pipelineRef:
    name: homelab
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
