apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    homelab.khuedoan.com/bao-secret: "true"
  annotations:
    secrets-webhook.security.bank-vaults.io/provider: bao
    secrets-webhook.security.bank-vaults.io/bao-role: {{ .Release.Namespace }}
    secrets-webhook.security.bank-vaults.io/bao-path: kubernetes
    secrets-webhook.security.bank-vaults.io/bao-serviceaccount: default
data:
  GRAFANA_SSO_CLIENT_SECRET: {{ "bao:secret/data/kanidm.grafana#client_secret" | b64enc | quote }}
