Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.network "public_network"
  config.vm.synced_folder "..", "/home/vagrant/homelab"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    pacman -Syu --noconfirm base-devel docker
    systemctl enable --now docker
    usermod -aG docker vagrant
  SHELL
end
