[book]
authors = ["Khue Doan"]
language = "en"
multilingual = false
src = "src"
title = "Khue's Homelab"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/khuedoan/homelab"
edit-url-template = "https://github.com/khuedoan/homelab/edit/master/docs/{path}"

# TODO deprecate this after 6 months
[output.html.redirect]
"/try-on-a-vm.html" = "/try-locally.html"
