when:
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  unit-tests:
    image: nixery.dev/shell/git/go/gcc/gnumake
    commands:
      - make -C toolbox test
      - make -C tests test
    when:
      - event: pull_request
        path:
          include:
            - 'toolbox/**'
            - 'tests/**'
            - '.woodpecker/static-checks.yaml'
    depends_on: []
