- hosts: localhost
  tasks:
    - name: Ensure required namespaces exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
        state: present
      loop:
        - cert-manager
        - cloudflared
        - external-dns
        - global-secrets
        - k8up-operator
        - monitoring-system
