apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: mongo
      app.kubernetes.io/name: telegram-bot
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: mongo
        app.kubernetes.io/name: telegram-bot
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true
        fsGroup: 999
      containers:
      - name: mongo
        image: mongo:4.4.18
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: telegram-bot-database
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: telegram-bot-database
                key: password
        args:
          # default parameters
          - --auth
          - --bind_ip_all
          - --setParameter
          # disable metrics
          - diagnosticDataCollectionEnabled=false
        resources:
          requests:
            cpu: 10m
            memory: 140Mi
          limits:
            cpu: 200m
            memory: 300Mi
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage-zfs
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage-zfs
        labels:
          backup: telegram-bot-zfs
      spec:
        storageClassName: zfs-local-dataset
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
