apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-drive-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-drive-pvc
spec:
  storageClassName: ""
  volumeName: seafile-drive-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti
